INCLUDE_DIRS = -I$(top_builddir)/third_party/include/codec            \
               -I$(top_builddir)/third_party/include/call

LIB_DIRS = -L$(top_builddir)/third_party/lib/codec \
           -L$(top_builddir)/third_party/lib/call